config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'users/profile', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'users/profile', to: 'users/registrations#profile_update', as: 'profile_update'  
  end
  root to: "home#index"
  get 'users/account'
  get 'rooms/posts'
  resources :rooms do
    collection do
      get 'search'
    end
  end
  post 'reservations/new'
  post 'reservations/create'
  get 'reservations/show'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :rooms, through: :reservations
  has_many :reservations

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  mount_uploader :user_image, UserImageUploader

  validates :name, presence: true
  validates :user_image, presence: true, on: :update
  validates :email, uniqueness: true, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  def profile_edit

  end

  def profile_update
    current_user.assign_attributes(account_update_params)
    if current_user.save
      redirect_to users_account_path, notice: "ユーザー情報を更新しました"      
    else
      render "profile_edit"
    end
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :user_image, :introduction])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!

  def account
    @user = current_user
  end

  def profile
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
  <ul>
    <li class="active"><a href="/users/account">アカウント</a></li>
    <li><a href="/users/profile">プロフィール</a></li>
  </ul>
</div>
<div class="col-lg-2 user-nav user-nav-mobile d-lg-none ">
  <ul>
    <li class="active"><a href="/users/account">アカウント</a></li>
    <li><a href="/users/profile">プロフィール</a></li>
  </ul>
</div>
    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>アカウント</h5>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <div class= "col-md-3" >メールアドレス</div>
            <div class="col-md-9"><%= @user.email%></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <div class= "col-md-3" >パスワード</div>
            <div class="col-md-9">*********</div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <%= link_to "編集", edit_user_registration_path , class:"col-md-2 btn btn-primary mx-3" %>
          </div>
        </div>          
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
  <ul>
    <li><a href="/users/account">アカウント</a></li>
    <li class="active"><a href="/users/profile">プロフィール</a></li>
  </ul>
</div>
<div class="col-lg-2 user-nav user-nav-mobile d-lg-none ">
  <ul>
    <li><a href="/users/account">アカウント</a></li>
    <li class="active"><a href="/users/profile">プロフィール</a></li>
  </ul>
</div>
    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
        <%= render "devise/shared/error_messages", resource: resource %>
        <div class="update-content">
          <div class="row">
            <h5>プロフィール</h5>
          </div>
        <div>
        <div class="update-content">
            <div class="row">
              <div class="col-md-6 offset-md-3">
                <div class="icon-box">
                  <% if @user.user_image? %>
                    <%= image_tag current_user.user_image.url,class:"icon-image host-icon"%>
                  <% else %>
                    <%= image_tag 'default_icon.jpg' ,class:"icon-image host-icon"%>
                  <% end %>                                  
                </div>                  
              </div>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :user_image, "アイコン画像", class:"col-md-3 required-a" %>
              <%= f.file_field :user_image, class:"mb-4 col-md-9"%>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :introduction, "自己紹介", class:"col-md-3 required-a" %>
              <%= f.text_area :introduction, rows:5, placeholder: "自己紹介を入力" ,class:"form-control mb-4 col-md-9" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
            <%= f.submit "更新", class:"col-md-2 btn btn-primary mx-3"%> 
            <%= link_to "アイコン画像の削除", users_profile_path, method: :delete, class:"btn btn-primary col-md-2 mx-3" %>           
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>