config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'users/profile', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'users/profile', to: 'users/registrations#profile_update', as: 'profile_update'  
  end
  root to: "home#index"
  get 'users/account'
  get 'rooms/posts'
  resources :rooms do
    collection do
      get 'search'
    end
  end
  post 'reservations/new'
  post 'reservations/create'
  get 'reservations/show'
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div>
    <ul style="color: red">
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p>© 2020 POTEPAN.INC.</p>
</footer>

app/views/shared/_header_nav.html.erb
<header class="header">
  <div class="header-inner">
    <div class="header-left-nav">
      <%= link_to image_tag('logo.png') , root_path %>
    </div>
    <div class="header-right-nav">
      <%= link_to "ログイン", new_user_session_path ,class: "btn btn-primary my-2 mx-3" %>
      <%= link_to "登録する", new_user_registration_path ,class: "btn btn-secondary" %>
    </div>
  </div>
</header>

app/views/shared/_my_header.html.erb
<header class="header">
  <div class="header-inner">
    <div class="header-left-nav">
      <%= link_to image_tag('logo.png') , root_path %>
      <%= search_form_for @q, url: search_rooms_path do |f| %>
        <div class="header-search d-lg-inline-block d-none">
          <%= f.search_field :address_cont, class: 'form-control', placeholder:"東京"%>
          <i class="fas fa-map-marker-alt"></i>      
        </div>
        <div class="header-search d-lg-inline-block d-none">
          <%= f.search_field :name_or_address_or_introduction_cont, class: 'form-control', placeholder:"キーワード"%>
          <i class="fas fa-search"></i> 
        </div>
        <%= submit_tag '探す' ,class:'d-none'%>
      <% end %>
    </div>
    <div class="header-right-nav">      
      <div class="nav-item d-sm-inline-block d-none"><%= current_user.name %></div>      
      <div class="nav-item">
        <% if current_user.user_image? %>
          <%= image_tag current_user.user_image.url,class:"icon-image host-icon mx-3 p-1 nav-trigger"%>
        <% else %>
          <%= image_tag 'default_icon.jpg' ,class:"icon-image host-icon mx-3 p-1 nav-trigger"%>
        <% end %>           
        <ul class="header-nav-menu" style="display: none;">
          <li><%= link_to "ルーム登録", new_room_path %></li>
          <li><%= link_to "予約済みルーム一覧", reservations_show_path %></li>
          <li><%= link_to "登録ルーム一覧", rooms_posts_path %></li>
          <li><%= link_to "設定" ,users_account_path %></li>            
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>            
        </ul>
      </div>      
    </div>
  </div>
</header>