config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'users/profile', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'users/profile', to: 'users/registrations#profile_update', as: 'profile_update'  
  end
  root to: "home#index"
  get 'users/account'
  get 'rooms/posts'
  resources :rooms do
    collection do
      get 'search'
    end
  end
  post 'reservations/new'
  post 'reservations/create'
  get 'reservations/show'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  def date_check
    end_date - start_date
  end

  def use_date
    date = date_check.to_i
    use_date = '使用日数：' + date.to_s + '日'
  end

  def total_amount
    room_price * person_num * date_check.to_i
  end
  
  validate :today_check?
  validate :start_end_check?
  validate :person_check?

  def today_check?
    errors.add(:start_date, "は本日以降を選択してください") if start_date.nil? || start_date < Date.today
  end

  def start_end_check?
    errors.add(:end_date, "は開始日以降を選択してください") if end_date.nil? || start_date >= end_date
  end

  def person_check?
    errors.add(:person_num, "は１人から選択してください") if person_num.nil? || person_num < 1
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservation = Reservation.new(reservation_params)
    if @reservation.invalid?
      flash[:alert] = @reservation.errors.full_messages.to_sentence
      redirect_back(fallback_location: rooms_path)
    end
  end

  def create 
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:notice] = "ルームを予約しました"
      redirect_to root_path
    else
      flash[:alert] = "予約に失敗しました"
      render 'new'
    end
  end

  def show
    @reservations = Reservation.where(user_id:current_user.id)
  end

  private
  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date ,:total_amount, :person_num, :user_id, :room_id, :room_price, :person_num)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  
end

app/views/reservations/new.html.erb
<%= render "shared/error", obj: @reservation %>
<% self.class.send(:include, ReservationsHelper) %>
<div class="container reservations-new">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="reservations-new-nav">
        <h4 class="reservations-new-check-content">予約内容確認</h4>
        <h5 class="price-icon"><%= @reservation.room.price%> / 日</h5>
        <div class="reservations-new-date-select">
          <%= form_for @reservation, method: :post, url: reservations_create_path do |f| %>
            <%= f.hidden_field :user_id %>
            <%= f.hidden_field :room_id %>  
            <%= f.hidden_field :person_num %> 
            <%= f.hidden_field :room_price %> 
            <%= f.label :start, "開始日"%>
            <%= f.date_field :start_date, class:"form-control mb-4" ,readonly:"true"%>
            <%= f.label :end, "終了日"%>
            <%= f.date_field :end_date, class:"form-control mb-4",readonly:"true" %>
            <h6 class="reservations-new-check-content"><%= @reservation.use_date %></h6>          
            <h6 class="reservations-new-check-content">人数：<%= @reservation.person_num %>人</h6>          
            <%= f.label :total_amount, "合計金額" %>            
            <%= f.text_field :total_amount, class:"form-control mb-4",readonly:"true" %>
            <p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>            
            <%= f.submit "予約する", class:"form-control btn btn-primary my-3" %>        
          <%end %>
            <%= link_to "戻る", :back, class:"form-control btn btn-secondary"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld room-posts">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr style="text-align:center;">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td >
            <% if reservation.room.room_image? %>
              <%= link_to image_tag(reservation.room.room_image.url,class:"room-posts-image"), controller: 'rooms', action: 'show' ,id: reservation.room_id%>
            <% else %>
              <%= link_to image_tag('default_icon.jpg',class:"room-posts-image"), controller: 'rooms', action: 'show' ,id: reservation.room_id %>  
            <% end %>
          </td>
          <td class="posts-name"><%= link_to reservation.room.name, controller: 'rooms', action: 'show' ,id: reservation.room_id %></td>
          <td class="posts-contents"><%= reservation.room.introduction%></td>
          <td class="price-icon"><%= reservation.total_amount%></td>
          <td><%= reservation.start_date.to_s(:date_jp) %></td>          
          <td><%= reservation.end_date.to_s(:date_jp) %></td>          
          <td><%= reservation.created_at.to_s(:datetime_jp) %></td>          
        </tr>
      <% end %>
    </tbody>
  </table>
</div>